use std::rc::Rc;

#[derive(Clone, Hash, Debug, PartialEq)]
pub enum Token {
    Print,
    If,
    Then,
    Else,
    Fi,
    For,
    Do,
    Done,
    While,
    Finish,
    Plus,
    Minus,
    Asterisk,
    FSlash,
    Percent,
    LT,
    LE,
    EQ,
    GE,
    GT,
    Let,
    AssignEq,
    Semicol,
    True,
    False,
    IntLit(i64),
    StringLit(Rc<str>),
    Ident(Rc<str>),
}

impl Token {
    pub fn kind(&self) -> &'static str {
        match self {
            Token::Print => "Print",
            Token::If => "If",
            Token::Then => "Then",
            Token::Else => "Else",
            Token::Fi => "Fi",
            Token::For => "For",
            Token::Do => "Do",
            Token::Done => "Done",
            Token::Plus => "Plus",
            Token::Semicol => "Semicol",
            Token::IntLit(_) => "Int",
            Token::Ident(_) => "Identity",
            Token::Minus => "Minus",
            Token::Asterisk => "Asterisk",
            Token::FSlash => "FSlash",
            Token::Percent => "Percent",
            Token::True => "True",
            Token::False => "False",
            Token::LT => "Less Than",
            Token::LE => "Less Than or Equal To",
            Token::EQ => "Equal To",
            Token::GE => "Greater Than or Equal To",
            Token::GT => "Greater Than",
            Token::Let => "Let",
            Token::AssignEq => "Assignment Equals",
            Token::While => "While",
            Token::Finish => "Finish",
            Token::StringLit(_) => "String Literal",
        }
    }
}
